### ISSUE TITLE
Authenticated User

### ISSUE THREAD

**Issue by Carmer** [scottfirestone/not_napster#18]
As a visitor
    When I visit "/"
    Then I should see a link for "Login"
    And when I click link "Create Account"
    And I fill in my desired credentials
    And I submit my information
    Then my current page should be "/dashboard"
    And I should see a message in the navbar that says "Logged in as SOME_USER"
    And I should see my profile information
    And I should not see a link for "Login"
    And I should see a link for "Logout"

```
And when I visit "/cart"
Then I should see all of the data that was there when I was not logged in
When I click "Logout"
Then I should see see "Login"
And I should not see "Logout"
```

**Comment by julsfelic** [comment]
Hey @Carmer. Should this all be one feature test or should we break out other seperate feature tests?

**Comment by Carmer** [comment]
@julsfelic - this can be one story. I think the key piece of this story is, `Then I should see all of the data that was there when I was not logged in` . This presumes there where items in the cart before the user logged in.
