### ISSUE TITLE
viewing artists page

### ISSUE THREAD

**Issue by Carmer** [scottfirestone/not_napster#24]
as an unauthenticated user 
when I visit "/:ARTIST_NAME'
I expect to see their albums available on the site

**Comment by julsfelic** [comment]
Yo @Carmer. So since we already have a dynamic /:GENRE_NAME is it possible to have a /:ARTIST_NAME without the two conflicting? I talked to Regis and we couldn't figure out how to do it without doing /artists/:ARTIST_NAME

**Comment by Carmer** [comment]
@julsfelic yes, just implement '/artist/:artist-name' lets talk about this tomorrow too
